name: Publish Release

on:
  push:
    branches:
      - main

jobs:
  main:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Publish Release
        uses: Leomotors/auto-publish-release@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TITLE: "My NPM Automation {VERSION}"
          VERSION_MUST_INCREASE: true
          ALWAYS_GENERATE_NOTES: true
